# Generated by Django 5.0.7 on 2024-08-02 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_category_alter_customuser_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('faculty_name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('title', models.CharField(max_length=200)),
                ('certification', models.FileField(upload_to='faculty_certificate')),
                ('experience', models.CharField(max_length=200)),
                ('price', models.BigIntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.customuser',),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
