# Generated by Django 5.0.7 on 2024-08-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_faculty_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
