# Generated by Django 5.0.7 on 2024-08-14 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_otpverification_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpverification',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrequest_faculty', to='accounts.faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrequest_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
