# Generated by Django 5.0.7 on 2024-08-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_facultymeetings_facultyvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_cat', to='accounts.category'),
        ),
    ]
